/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import javax.swing.JOptionPane;
import sk.stu.fiit.controllers.CustomerController;
import sk.stu.fiit.exceptions.BlankFields;
import sk.stu.fiit.model.Customer;

/**
 *
 * @author jarni
 */
public class AddCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    
    
    public AddCustomer() {
        initComponents();
    }
    
    private MainPage mainPage;
    private boolean editing = false;
    private Customer cus;
    
    public void initializeEdit(Customer cus){
        lblHeading.setText("Úprava zákazníka");
        tfdName.setText(cus.getName());
        tfdCity.setText(cus.getCity());
        tfdPSC.setText(cus.getPsc());
        tfdStreet.setText(cus.getStreet());
        editing = true;
        this.cus = cus;
    }
    
    public void initializeParent(MainPage mainPage){
        this.mainPage = mainPage;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblStreet = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblPSC = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();
        tfdName = new javax.swing.JTextField();
        tfdStreet = new javax.swing.JTextField();
        tfdCity = new javax.swing.JTextField();
        tfdPSC = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblName.setText("Meno a priezvisko");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        lblStreet.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblStreet.setText("Ulica, č.d.");
        getContentPane().add(lblStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        lblCity.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblCity.setText("Mesto");
        getContentPane().add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        lblPSC.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblPSC.setText("PSČ");
        getContentPane().add(lblPSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        lblHeading.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblHeading.setText("Pridanie zákazníka");
        getContentPane().add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));
        getContentPane().add(tfdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 58, 260, 30));
        getContentPane().add(tfdStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 260, 30));
        getContentPane().add(tfdCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 260, 30));
        getContentPane().add(tfdPSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 260, -1));

        btnSave.setText("Uložiť zákazníka");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 120, -1));

        btnCancel.setText("Zrušiť");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    CustomerController cuscon = new CustomerController();
    
    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        String name = tfdName.getText();
        String city = tfdCity.getText();
        String street = tfdStreet.getText();
        String psc = tfdPSC.getText();
        
        try{
            if (editing)
                cuscon.editCustomer(cus, name, city, street, psc);
            else
                cuscon.addCustomer(name, city, street, psc);
            
            dispose();
            mainPage.initializeCustomerTable();
        }
        catch(BlankFields e){
            JOptionPane.showMessageDialog(rootPane, "Musite vyplnit vsetky polia", "Nevyplnene polia", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPSC;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JTextField tfdCity;
    private javax.swing.JTextField tfdName;
    private javax.swing.JTextField tfdPSC;
    private javax.swing.JTextField tfdStreet;
    // End of variables declaration//GEN-END:variables
}
