/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sk.stu.fiit.data.Data;
import sk.stu.fiit.model.Commodity;

/**
 *
 * @author jarni
 */
public class Zoznam extends javax.swing.JFrame implements TablesCommodity{
    /**
     * Creates new form Zoznam
     */
    //private List<Commodity> CommoditiesInvoice = new ArrayList<>();
    private MainPage parent;
    
    public Zoznam() {
        initComponents();
    }
    
    public void initializeZoznam(MainPage mainPage){
        parent = mainPage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddComInv = new javax.swing.JButton();
        txfNumber = new javax.swing.JTextField();
        lblNumber = new javax.swing.JLabel();
        btnAddNewComm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        List<String> columns = new ArrayList<String>();
        List<String[]> values = new ArrayList<String[]>();

        for (Commodity com: Data.getAllCommodities()){
            values.add(new String[] {com.getName(), com.getDesc(), String.valueOf(com.getPrice() / 100.0)});
        }

        columns.add("Názov");
        columns.add("Opis tovaru");
        columns.add("Cena");

        TableModel tableModel = new DefaultTableModel(values.toArray(new Object[][] {}), columns.toArray());
        jTable1.setModel(tableModel);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 220));

        btnAddComInv.setText("Pridať k faktúre");
        btnAddComInv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddComInvMouseClicked(evt);
            }
        });
        getContentPane().add(btnAddComInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));
        getContentPane().add(txfNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 80, -1));

        lblNumber.setText("Množstvo:");
        getContentPane().add(lblNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        btnAddNewComm.setText("Pridať nový tovar");
        btnAddNewComm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNewCommMouseClicked(evt);
            }
        });
        getContentPane().add(btnAddNewComm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddComInvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddComInvMouseClicked
        int row = jTable1.getSelectedRow();
        
        if (row > -1){
            String name = String.valueOf(jTable1.getValueAt(row, 0));            
            String desc = String.valueOf(jTable1.getValueAt(row, 1));
            
            try {
                String price = String.valueOf(jTable1.getValueAt(row, 2));                
                double priceN = Double.parseDouble(price);              
                int cena = (int) (priceN * 100);
                
                String number = txfNumber.getText();
                int mnozstvo = Integer.parseInt(number);
                Commodity com = new Commodity(name, desc, cena, mnozstvo);
                
                boolean add = true;
                for (Commodity commodity: parent.getInvoiceComs()){
                    if (commodity.getName().equals(com.getName()) && commodity.getDesc().equals(com.getDesc()) && commodity.getPrice() == com.getPrice())
                        add = false;
                        commodity.setNumber(mnozstvo);
                }
                
                if (add)
                    parent.getInvoiceComs().add(com);
                
                parent.initializeCommoditiesTableInvoice();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Pole množstvo musí obsahovať celé kladné číslo", "Chyba.", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Vyberte tovar, ktorý si prajete vložiť do faktúry.", "Nevybraný tovar", JOptionPane.ERROR_MESSAGE);
        
        /*for (int i=0; i < rows.length; i++){
            String name = String.valueOf(jTable1.getValueAt(rows[i], 0));            
            String desc = String.valueOf(jTable1.getValueAt(rows[i], 1));
            try {
                System.out.println(parent);
                System.out.println(parent.getInvoiceComs());
                String price = String.valueOf(jTable1.getValueAt(rows[i], 2));                
                double priceN = Double.parseDouble(price);              
                int cena = (int) (priceN * 100);
                System.out.println("Som za cenu");
                
                String number = txfNumber.getText();
                System.out.println("number = " + number);
                int mnozstvo = Integer.parseInt(number);
                System.out.println("Si nerozparsoval");
                Commodity com = new Commodity(name, desc, cena, mnozstvo);
                
                boolean add = true;
                System.out.println("Pred forloopom");
                for (Commodity comm: parent.getInvoiceComs()){
                    if (comm.getName().equals(com.getName()) && comm.getDesc().equals(com.getDesc()) && comm.getPrice() == com.getPrice())
                        add = false;
                }
                
                if (add)
                    parent.getInvoiceComs().add(com);
                
                parent.initializeCommoditiesTableInvoice();
                
            } catch (Exception e) {
                System.out.println("Toto asi nenastane");
            }            
        }*/
    }//GEN-LAST:event_btnAddComInvMouseClicked

    private void btnAddNewCommMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewCommMouseClicked
        AddCommodity commodity = new AddCommodity();
        commodity.setVisible(true);
        commodity.initializeAddCommodity(this);
    }//GEN-LAST:event_btnAddNewCommMouseClicked

    public void initializeTable(){
        List<String> columns = new ArrayList<String>();
        List<String[]> values = new ArrayList<String[]>();

        for (Commodity com: Data.getAllCommodities()){
            values.add(new String[] {com.getName(), com.getDesc(), String.valueOf(com.getPrice() / 100.0)});
        }

        columns.add("Názov");
        columns.add("Opis tovaru");
        columns.add("Cena");

        TableModel tableModel = new DefaultTableModel(values.toArray(new Object[][] {}), columns.toArray());
        jTable1.setModel(tableModel);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zoznam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zoznam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zoznam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zoznam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zoznam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddComInv;
    private javax.swing.JButton btnAddNewComm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JTextField txfNumber;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initializeCommodityTable() {
        List<String> columns = new ArrayList<String>();
        List<String[]> values = new ArrayList<String[]>();

        for (Commodity com: Data.getAllCommodities()){
            values.add(new String[] {com.getName(), com.getDesc(), String.valueOf(com.getPrice() / 100.0)});
        }

        columns.add("Názov");
        columns.add("Opis tovaru");
        columns.add("Cena");

        TableModel tableModel = new DefaultTableModel(values.toArray(new Object[][] {}), columns.toArray());
        jTable1.setModel(tableModel);    }
}
